/* get list user */
export const GET_DATA_USER_RESQUEST = "GET_DATA_USER_RESQUEST";
export const GET_DATA_USER_SUCCESS = "GET_DATA_USER_SUCCESS";
export const GET_DATA_USER_FAIL = "GET_DATA_USER_FAIL";


/* delete user */
export const DELETE_USER_RESQUEST = "DELETE_USER_RESQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
/* update user */
export const UPDATE_USER_RESQUEST = "UPDATE_USER_RESQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
/* Add data user */
export const ADD_USER_RESQUEST = "ADD_USER_RESQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
