export const GET_DATA_MENU_RESQUEST = "GET_DATA_MENU_RESQUEST";
export const GET_DATA_MENU = "GET_DATA_MENU";
export const ADD_DATA_MENU = "ADD_DATA_MENU";
export const DELETE_DATA_MENU = "DELETE_DATA_MENU";
export const UPDATE_DATA_MENU = "UPDATE_DATA_MENU";
export const GET_DATA_DETAIL_MENU = "GET_DATA_DETAIL_MENU";
export const UPDATE_FIELD_DATA_MENU = "UPDATE_FIELD_DATA_MENU";
export const GET_DATA_SUB_MENU = "GET_DATA_SUB_MENU";
export const DELETE_SUB_DATA_MENU = "GET_DATA_SUB_MENU";
export const ADD_SUB_DATA_MENU = "ADD_SUB_DATA_MENU";
export const DELETE_SUB_MENU = "DELETE_SUB_MENU";




