export const GET_DATA_MENU_RESQUEST = "GET_DATA_MENU_RESQUEST";
export const GET_DATA_MENU = "GET_DATA_MENU";

export const ADD_DATA_MENU = "ADD_DATA_MENU";
export const DELETE_DATA_MENU = "DELETE_DATA_MENU";
export const UPDATE_DATA_MENU = "UPDATE_DATA_MENU";

export const GET_DATA_DETAIL_MENU = "GET_DATA_DETAIL_MENU";


